import type { RepoListItem } from '@/types'

export const CATEGORIES = ['all', 'AI/ML', 'SWE'] as const

export const REPOS: RepoListItem[] = [
  // AI/ML (50)
  { full_name: 'tensorflow/tensorflow', category: 'AI/ML' },
  { full_name: 'pytorch/pytorch', category: 'AI/ML' },
  { full_name: 'huggingface/transformers', category: 'AI/ML' },
  { full_name: 'openai/openai-python', category: 'AI/ML' },
  { full_name: 'langchain-ai/langchain', category: 'AI/ML' },
  { full_name: 'AUTOMATIC1111/stable-diffusion-webui', category: 'AI/ML' },
  { full_name: 'ollama/ollama', category: 'AI/ML' },
  { full_name: 'microsoft/autogen', category: 'AI/ML' },
  { full_name: 'open-webui/open-webui', category: 'AI/ML' },
  { full_name: 'ggerganov/llama.cpp', category: 'AI/ML' },
  { full_name: 'comfyanonymous/ComfyUI', category: 'AI/ML' },
  { full_name: 'huggingface/diffusers', category: 'AI/ML' },
  { full_name: 'facebookresearch/llama', category: 'AI/ML' },
  { full_name: 'imartinez/privateGPT', category: 'AI/ML' },
  { full_name: 'run-llama/llama_index', category: 'AI/ML' },
  { full_name: 'chroma-core/chroma', category: 'AI/ML' },
  { full_name: 'qdrant/qdrant', category: 'AI/ML' },
  { full_name: 'mlflow/mlflow', category: 'AI/ML' },
  { full_name: 'ray-project/ray', category: 'AI/ML' },
  { full_name: 'keras-team/keras', category: 'AI/ML' },
  { full_name: 'scikit-learn/scikit-learn', category: 'AI/ML' },
  { full_name: 'dmlc/xgboost', category: 'AI/ML' },
  { full_name: 'openai/whisper', category: 'AI/ML' },
  { full_name: 'microsoft/DeepSpeed', category: 'AI/ML' },
  { full_name: 'microsoft/promptflow', category: 'AI/ML' },
  { full_name: 'deepseek-ai/DeepSeek-V3', category: 'AI/ML' },
  { full_name: 'gradio-app/gradio', category: 'AI/ML' },
  { full_name: 'streamlit/streamlit', category: 'AI/ML' },
  { full_name: 'crewAIInc/crewAI', category: 'AI/ML' },
  { full_name: 'unslothai/unsloth', category: 'AI/ML' },
  { full_name: 'EleutherAI/gpt-neox', category: 'AI/ML' },
  { full_name: 'facebookresearch/faiss', category: 'AI/ML' },
  { full_name: 'openai/gym', category: 'AI/ML' },
  { full_name: 'BerriAI/litellm', category: 'AI/ML' },
  { full_name: 'nomic-ai/gpt4all', category: 'AI/ML' },
  { full_name: 'xtekky/gpt4free', category: 'AI/ML' },
  { full_name: 'lm-sys/FastChat', category: 'AI/ML' },
  { full_name: 'vllm-project/vllm', category: 'AI/ML' },
  { full_name: 'Significant-Gravitas/AutoGPT', category: 'AI/ML' },
  { full_name: 'microsoft/semantic-kernel', category: 'AI/ML' },
  { full_name: 'openai/evals', category: 'AI/ML' },
  { full_name: 'karpathy/nanoGPT', category: 'AI/ML' },
  { full_name: 'haotian-liu/LLaVA', category: 'AI/ML' },
  { full_name: 'microsoft/LightGBM', category: 'AI/ML' },
  { full_name: 'google/jax', category: 'AI/ML' },
  { full_name: 'lutzroeder/netron', category: 'AI/ML' },
  { full_name: 'openai/CLIP', category: 'AI/ML' },
  { full_name: 'facebookresearch/segment-anything', category: 'AI/ML' },
  { full_name: 'microsoft/TaskMatrix', category: 'AI/ML' },
  { full_name: 'skypilot-org/skypilot', category: 'AI/ML' },

  // SWE (50)
  { full_name: 'vercel/next.js', category: 'SWE' },
  { full_name: 'facebook/react', category: 'SWE' },
  { full_name: 'vuejs/vue', category: 'SWE' },
  { full_name: 'angular/angular', category: 'SWE' },
  { full_name: 'sveltejs/svelte', category: 'SWE' },
  { full_name: 'denoland/deno', category: 'SWE' },
  { full_name: 'nodejs/node', category: 'SWE' },
  { full_name: 'golang/go', category: 'SWE' },
  { full_name: 'rust-lang/rust', category: 'SWE' },
  { full_name: 'microsoft/vscode', category: 'SWE' },
  { full_name: 'torvalds/linux', category: 'SWE' },
  { full_name: 'kubernetes/kubernetes', category: 'SWE' },
  { full_name: 'hashicorp/terraform', category: 'SWE' },
  { full_name: 'astro-build/astro', category: 'SWE' },
  { full_name: 'vitejs/vite', category: 'SWE' },
  { full_name: 'supabase/supabase', category: 'SWE' },
  { full_name: 'prisma/prisma', category: 'SWE' },
  { full_name: 'trpc/trpc', category: 'SWE' },
  { full_name: 'shadcn-ui/ui', category: 'SWE' },
  { full_name: 'tailwindlabs/tailwindcss', category: 'SWE' },
  { full_name: 'nestjs/nest', category: 'SWE' },
  { full_name: 'fastify/fastify', category: 'SWE' },
  { full_name: 'expressjs/express', category: 'SWE' },
  { full_name: 'tiangolo/fastapi', category: 'SWE' },
  { full_name: 'pallets/flask', category: 'SWE' },
  { full_name: 'django/django', category: 'SWE' },
  { full_name: 'rails/rails', category: 'SWE' },
  { full_name: 'laravel/laravel', category: 'SWE' },
  { full_name: 'docker/compose', category: 'SWE' },
  { full_name: 'neovim/neovim', category: 'SWE' },
  { full_name: 'ohmyzsh/ohmyzsh', category: 'SWE' },
  { full_name: 'junegunn/fzf', category: 'SWE' },
  { full_name: 'sharkdp/bat', category: 'SWE' },
  { full_name: 'BurntSushi/ripgrep', category: 'SWE' },
  { full_name: 'astral-sh/uv', category: 'SWE' },
  { full_name: 'astral-sh/ruff', category: 'SWE' },
  { full_name: 'pydantic/pydantic', category: 'SWE' },
  { full_name: 'pytest-dev/pytest', category: 'SWE' },
  { full_name: 'celery/celery', category: 'SWE' },
  { full_name: 'grafana/grafana', category: 'SWE' },
  { full_name: 'prometheus/prometheus', category: 'SWE' },
  { full_name: 'traefik/traefik', category: 'SWE' },
  { full_name: 'sindresorhus/awesome', category: 'SWE' },
  { full_name: 'public-apis/public-apis', category: 'SWE' },
  { full_name: 'gothinkster/realworld', category: 'SWE' },
  { full_name: 'tmux/tmux', category: 'SWE' },
  { full_name: 'git/git', category: 'SWE' },
  { full_name: 'microsoft/terminal', category: 'SWE' },
  { full_name: 'ziglang/zig', category: 'SWE' },
  { full_name: 'nickvdyck/webbundle', category: 'SWE' },
]

export const SYNC_INTERVAL_HOURS = 12
export const BATCH_SIZE = 10
export const BATCH_DELAY_MS = 300
